[build]
publish = "public"
command = "sh do hugo"

[build.environment]
HUGO_VERSION = "0.164.0"
NODE_VERSION = "22.22.0"

[context.production]
publish = "public"
command = "sh do hugo"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
